// Importar estilos PRIMERO (orden importante)
import './assets/base.css'
// Importar estilos de Swiper
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'

import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { OhVueIcon, addIcons } from 'oh-vue-icons'
import {
  HiHome,
  HiUsers,
  HiViewGrid,
  HiShoppingBag,
  HiPlus,
  HiPencil,
  HiTrash,
  BiCamera,
  HiRefresh,
  HiSearch,
  HiChevronDown,
  HiChevronUp,
  HiExclamationCircle,
  HiShoppingCart,
  HiArrowLeft,
  BiStarFill,
  HiCalendar,
  HiSun,
  HiMoon,
  FaUserCircle,
  MdLogoutOutlined,
  IoPersonAddSharp,
  FaBoxes,
  RiCoupon2Line,
  HiXCircle,
  HiBadgeCheck,
  HiCheckCircle,
  HiClipboardCopy,
  FaCreditCard,
  HiLocationMarker,
  HiGlobe,
  HiOfficeBuilding,
  HiClock,
  HiCube,
  HiCollection,
  HiColorSwatch,
  HiAdjustments,
  HiArrowsExpand,
  HiMinus,
  HiMail,
  HiUserCircle,
  HiKey,
  HiHeart,
  HiCreditCard,
  HiTruck,
  // Category icons
  GiSmartphone,
  CoTablet,
  FaTshirt,
  HiBookOpen,
  BiKeyboard,
  BiMouse,
  MdSportssoccer,
  MdCable,
  BiSmartwatch,
  HiCake,
  HiMusicNote,
  GiConsoleController,
  GiAirplane,
  MdChair,
  GiDiamondRing,
  GiCat,
  FaBaby,
  GiCookingPot,
  BiLaptop,
  FcElectronics,
  MdSettingsinputcomponent,
  RiHomeWifiLine,
  LaHeadphonesSolid,
} from 'oh-vue-icons/icons'

import App from './App.vue'
import router from './router'

// Add icons to the library
addIcons(
  HiHome,
  HiUsers,
  HiViewGrid,
  HiShoppingBag,
  HiPlus,
  HiPencil,
  HiTrash,
  BiCamera,
  HiRefresh,
  HiSearch,
  HiChevronDown,
  HiChevronUp,
  HiExclamationCircle,
  HiShoppingCart,
  HiArrowLeft,
  BiStarFill,
  HiCalendar,
  HiSun,
  HiMoon,
  FaUserCircle,
  MdLogoutOutlined,
  IoPersonAddSharp,
  FaBoxes,
  RiCoupon2Line,
  HiXCircle,
  HiBadgeCheck,
  HiCheckCircle,
  HiClipboardCopy,
  FaCreditCard,
  HiLocationMarker,
  HiGlobe,
  HiOfficeBuilding,
  HiClock,
  CoTablet,
  HiCube,
  HiCollection,
  HiColorSwatch,
  HiAdjustments,
  HiArrowsExpand,
  HiMinus,
  HiMail,
  HiUserCircle,
  HiKey,
  BiKeyboard,
  HiHeart,
  HiTruck,
  // Category icons
  GiSmartphone,
  FaTshirt,
  HiBookOpen,
  BiSmartwatch,
  MdCable,
  HiCake,
  HiMusicNote,
  GiConsoleController,
  GiAirplane,
  MdChair,
  BiMouse,
  GiDiamondRing,
  GiCat,
  FaBaby,
  GiCookingPot,
  BiLaptop,
  FcElectronics,
  MdSettingsinputcomponent,
  RiHomeWifiLine,
  LaHeadphonesSolid
)

const app = createApp(App)

// Register OhVueIcon component globally
app.component('v-icon', OhVueIcon)

app.use(createPinia())
app.use(router)

app.mount('#app')
